### ISSUE TITLE
Paid Work

### ISSUE THREAD

**Issue by studystudystudyhard** [jimmybow/Flask_template_auth_with_Dash#1]
Hey jimmy, i have some plotly dash custom component work. Your email isn't published anymore. If you are interested please email me at studystudystudyhard@hotmail.com.

**Comment by jimmybow** [comment]
hi, 
you can share your own dash component on plotly forum, and I also publish my email now.

**Comment by studystudystudyhard** [comment]
What i meant is i need some custom component made, are you interested in getting paid to make one for me.

**Comment by jimmybow** [comment]
no thanks, actually I am not good at front-end design.
