### ISSUE TITLE
Dynamic Layout

### ISSUE THREAD

**Issue by imranshabbir** [jimmybow/Flask_template_auth_with_Dash#2]
Hi Jimmy,

Nice work done, can you please comment how can we change it to serve the dynamic layout. At the moment whatever dash layout we are assigning during application startup. It will not change as apply_layout_with_authentication function will be called on first load.

**Comment by jimmybow** [comment]
Hi imranshabbir,
for each dashboard, you can just set your own **layout** and **app.callback** function to make dynamic layout, see [Dashboard/Dash_App1.py](https://github.com/jimmybow/Flask_template_auth_with_Dash/blob/master/Dashboard/Dash_App1.py) for example. 
the **apply_layout_with_authentication** method is always fixed.
