### ISSUE TITLE
css file for dash app

### ISSUE THREAD

**Issue by HerrTeuer** [jimmybow/Flask_template_auth_with_Dash#3]
Hi Jimmybow,
firstly thank you for sharing such great work!
I want to ask if we can apply custom.css to the dash app?

for example, I have a dash app with a function to generate html element dynamically:

```
def generateEmptyProjectOverview():
    return [
        html.Table(
            children=
                [html.Colgroup([
                    html.Col(), html.Col(id="specCol1"), html.Col(), html.Col(id="specCol2")]
                )] +
                # 
                [ html.Tr([ 
                    html.Td(html.Img(src="/static/images/car_s.png")), html.Td( html.H5("vehicle number")),
                    html.Td(html.Img(src="/static/images/calibration_s.png")), html.Td( html.H5("calibration dataset number")) ])] +
                # 
                [ html.Tr([
                    html.Td(html.Img(src="/static/images/distance_s.png")), html.Td( html.H5("total distance")),
                    html.Td(html.Img(src="/static/images/warning_s.png")), html.Td( html.H5("warning labels")) ]) ],
            className = "tb_projectoverview",
        )
    ]
```

in static/build/css/custom.css file, the style is defined as follows:
```
.tb_projectoverview {
    margin: auto;
}

.tb_projectoverview td {
    width: 100px;
    height: 120px;
    text-align: left;
    border: 0;
    color: #595959;
}


#specCol1, #specCol2{
    width: 350px;
}
```
but these style will not be applyed to the html elements.

**Comment by jimmybow** [comment]
Hi, 
you need to place your css file in a folder named **'assets'**, you can see the [document](https://dash.plot.ly/external-resources) of dash about including local CSS and JavaScript.
https://dash.plot.ly/external-resources

**Comment by HerrTeuer** [comment]
thank you very much!

I change the function `def Add_Dash(server):`, add `__name__` to Dash()
`app = Dash(__name__, server=server, url_base_pathname=url_base)`

then add '**customer.css**' folder under this directory **Flask_template_auth_with_Dash/Dashboard/assets/custom.css**

then everything works well!
