### ISSUE TITLE
differences from original flask-gentelella

### ISSUE THREAD

**Issue by glw** [jimmybow/Flask_template_auth_with_Dash#4]
Hi Jimmy, great job on getting dash working with flask.

I had a couple questions for you:
1. I was comparing your project to the original flask-gentelalla project and I noticed you took out docker and nginx. Where there specific reasons for this? Was it because you used herouku or pythoneverywhere and didnt need it in those environements?

2. In your version how do you include postrgresql as the backend?

Thanks!

**Comment by jimmybow** [comment]
Hi, for your questions:
1. this project is lightweight and focus on the integration of dash and flask app and auth with flask_login, so never consider using tools of docker and nginx
2. you can config your DB connection info in **/configs/config.py**
and apply your config to your flask app, see https://github.com/jimmybow/Flask_template_auth_with_Dash/blob/master/run.py#L14

**Comment by glw** [comment]
Thanks @jimmybow !
